language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - "psql -c 'create database storemanagertestdb;' -U postgres"
  - "psql -c 'CREATE USER calvin WITH PASSWORD '310892'; -U postgres"

#command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run tests
script:
  - nosetests --with-coverage --cover-package=app
  - coverage report

# push report to code climate and coveralls.io
after_success:
  - coveralls